### PR TITLE
WIP: Add compiled regex filters

### PR DESCRIPTION
**Pull request by satabin**
**This is work in progress, not intended to be merged yet, just to get CI feedback**

The idea behind compiled regular expressions filters is that they are all run in parallel, avoiding to iterate over all possible filters at each step. This should improve greatly performances when regex token filter resources are big.

The supported regular expression language of the underlying engine includes:
 - single character
 - character sets, e.g. `[a-z]`
 - any character `.`
 - greedy optional pattern `?`
 - greedy repetition `*` and `+`
 - greedy bounded repetitions, e.g. `regex{3, 6}`
 - capturing groups `(regex)`
 - simple name character sets `\d`, `\s`, `\w`
 - named character class,  e.g `\p{Punct}`
 - word lists, e.g. `\p{WordList(MyWords)}`

The regular expression engine is based on a VM approach as described by [Russ Cox](https://swtch.com/~rsc/regexp/) allowing for matching inputs linearly wrt. the input size and independently of the regular expression  complexity.

Regular expressions are compiled with unicode support and may be compiled with a case and diacritics insensitive flag.

### CODE REVIEW

**Comment by urieli** [comment]
When I compile the attached token_filters2.txt file, and then use it to analyse the attached frTestSimple.txt file, I get an error.
Commands:
`--compileRegexFilters --compiledFiltersFile=token_filters2.filt`
`--analyse --inFile=frTestSimple.txt --outFile=frTestSimple_tok.tal --endModule=tokeniser` with config file pointing at compiled token filters:

```
talismane {
	core {
		locale = fr
		
		annotators {	
			compiled-token-filters = [
				"token_filters2.filt"
			]
		}
		
		tokeniser {
			type = simple
		}
	}
}
```

Error:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.joliciel.talismane.sentenceAnnotators.CompiledRegexAnnotators.annotate(CompiledRegexAnnotators.java:150)
	at com.joliciel.talismane.sentenceAnnotators.CompiledRegexAnnotators.annotate(CompiledRegexAnnotators.java:1)
	at com.joliciel.talismane.Talismane.analyse(Talismane.java:442)
	at com.joliciel.talismane.TalismaneMain.execute(TalismaneMain.java:602)
	at com.joliciel.talismane.TalismaneMain.main(TalismaneMain.java:561)
```

[token_filters2.txt](https://github.com/joliciel-informatique/talismane/files/804066/token_filters2.txt)
[frTestSimple.txt](https://github.com/joliciel-informatique/talismane/files/804068/frTestSimple.txt)

**Comment by satabin** [comment]
Right, the serializer forgets about the match identifier, I will fix it.

**Comment by satabin** [comment]
@urieli commit b7eeb69 should fix the problem.

**Comment by urieli** [comment]
First issue fixed. Another issue now. When there is a regex with an explicit group, other regexes no longer match.

Using the same commands as before but for the files attached below, the "j'" regex no longer matches sentence one.

On this row: https://github.com/joliciel-informatique/talismane/pull/23/files#diff-604d3db7ff13fe177928f75901f49254R150

The groupIndex is set to 1, but the match only matches on group 0.

[token_filters3.txt](https://github.com/joliciel-informatique/talismane/files/811296/token_filters3.txt)
[frTestSimple.txt](https://github.com/joliciel-informatique/talismane/files/811298/frTestSimple.txt)

**Pull request closed without merging**
