### PR TITLE
Delete default logging configuration

### PR DESCRIPTION
**Pull request by satabin**
When Talismane is used as a library, this default logging configuration with DEBUG
level for all joliciel classes pollutes the application logs. Moreover, it is not the role of a library
to define the default logging configuration with some log file and an arbitrary rolling
strategy, let the client application do that.

### CODE REVIEW

**Comment by urieli** [comment]
The default-logback.xml file is not used by the library: it is only used by Talismane when run as a standalone application from the command-line.

If it is removed, the configureLogging code has to be corrected, to remove the "null" branch at:
https://github.com/joliciel-informatique/talismane/blob/master/talismane_utils/src/main/java/com/joliciel/talismane/utils/LogUtils.java#L187

Also, the various callers at:
https://github.com/joliciel-informatique/talismane/search?utf8=%E2%9C%93&q=configureLogging
Need to be corrected to only call configureLogging when a file is actually provided.

**Comment by satabin** [comment]
This is a weird use of logback. The library usually relies on the `loback.xml` file being in the classpath and not loaded explicitly in code. Any reason why it is done this way?

**Comment by urieli** [comment]
The reason here is to accommodate non-expert users of Talismane as a command-line application.

The problem here is that java `-cp` option is incompatible with the `-jar` option. And the Talismane JAR files contain the full classpath in their manifest file precisely in order to simplify running Talismane from the command line using the `-jar` option.

Adding a `logback.xml` file to the classpath, when running Talismane as a standalone from the command line, would involve copying the full classpath from inside the JAR's manifest file and then running `java -cp` instead of `java -jar`, adding `logback.xml` to the classpath. This is far too complex.

**Comment by urieli** [comment]
Fixed as described above with commit https://github.com/joliciel-informatique/talismane/commit/4a47366c951daedb52bf8b41958d6d5378bf4837

**Pull request closed without merging**
